CREATE TABLE purchase_lot (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holding_id   BIGINT         NOT NULL,
    shares       DECIMAL(19, 6) NOT NULL,
    price        DECIMAL(19, 4) NOT NULL,
    purchased_on DATE           NOT NULL,
    CONSTRAINT fk_purchase_lot_holding FOREIGN KEY (holding_id) REFERENCES holding (id)
);
